---
# tasks file for ansible-role-cassandra
- include: install/repo/debian.yml
  when: ansible_os_family == 'Debian' and cassandra_manage_repo
  tags: [cassandra.install, install, cassandra.repo, repo]

- name: stop cassandra from running with default config
  lineinfile: dest=/etc/sensitive_services line=cassandra state=present create=yes
  when: ansible_os_family == 'Debian'
  tags: [package, cassandra.package, cassandra.install, install]

- include: install/debian.yml
  when: ansible_os_family == 'Debian'
  tags: [package, cassandra.package, cassandra.install, install]

- include: configure.yml
  tags: [configure, cassandra.configure]

- name: Remove cassandra from /etc/sensitive_servies to enable automated starts
  lineinfile: dest=/etc/sensitive_services line=cassandra state=absent
  when: ansible_os_family == 'Debian'
